#!/bin/bash
# Builds deploy/runtime.env from SSM Parameter Store using the instance's IAM role.
# Usage: fetch_runtime_env.sh <control|dev>
#
# Secrets never land in the repo, images, or user-data: this file is generated on the
# instance at boot/deploy time with 0600 permissions and consumed via `env_file`.
set -euo pipefail

ROLE="${1:?usage: fetch_runtime_env.sh <control|dev>}"
AWS_REGION="${AWS_REGION:-ap-south-1}"
PARAM_PATH="${AIRFLOW_PARAM_PATH:-/dws/airflow}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUT="$SCRIPT_DIR/runtime.env"

get_param() {
  aws ssm get-parameter --region "$AWS_REGION" --name "$1" --with-decryption \
    --query 'Parameter.Value' --output text
}

FERNET_KEY=$(get_param "$PARAM_PATH/fernet_key")
WEBSERVER_SECRET_KEY=$(get_param "$PARAM_PATH/webserver_secret_key")
DB_PASSWORD=$(get_param "$PARAM_PATH/postgres_password")
REDIS_PASSWORD=$(get_param "$PARAM_PATH/redis_password")
ADMIN_PASSWORD=$(get_param "$PARAM_PATH/webserver_admin_password")
ALERT_TOPIC_ARN=$(get_param "$PARAM_PATH/alert_topic_arn")
TASK_LOG_GROUP_ARN=$(get_param "$PARAM_PATH/task_log_group_arn")

if [ "$ROLE" = "control" ]; then
  DB_HOST=postgres
  REDIS_HOST=redis
else
  CONTROL_IP=$(get_param "$PARAM_PATH/control_private_ip")
  DB_HOST="$CONTROL_IP"
  REDIS_HOST="$CONTROL_IP"
fi

umask 077
{
  echo "# Generated by fetch_runtime_env.sh - do not commit."
  echo "AIRFLOW__CORE__FERNET_KEY=$FERNET_KEY"
  echo "AIRFLOW__WEBSERVER__SECRET_KEY=$WEBSERVER_SECRET_KEY"
  echo "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$DB_PASSWORD@$DB_HOST:5432/airflow"
  echo "AIRFLOW__CELERY__BROKER_URL=redis://:$REDIS_PASSWORD@$REDIS_HOST:6379/0"
  echo "AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:$DB_PASSWORD@$DB_HOST:5432/airflow"
  echo "POSTGRES_PASSWORD=$DB_PASSWORD"
  echo "REDIS_PASSWORD=$REDIS_PASSWORD"
  echo "_AIRFLOW_WWW_USER_PASSWORD=$ADMIN_PASSWORD"
  echo "SNS_ALERT_TOPIC_ARN=$ALERT_TOPIC_ARN"
  echo "AIRFLOW__LOGGING__REMOTE_LOGGING=True"
  echo "AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=cloudwatch://$TASK_LOG_GROUP_ARN"
  echo "AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=aws_default"
  echo "AWS_REGION=$AWS_REGION"
  echo "AWS_DEFAULT_REGION=$AWS_REGION"
  # Non-sensitive project settings from the repo .env (excluding local-only AWS_PROFILE,
  # which must NOT be set on EC2 - the instance role provides credentials).
  grep -E '^(SNOWFLAKE_|S3_|DBT_)' "$REPO_ROOT/.env" 2>/dev/null || true
} > "$OUT"

echo "wrote $OUT for role=$ROLE"
