name: Terraform Validate

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  TF_VAR_snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
  TF_VAR_snowflake_private_key_path: ${{ github.workspace }}/secrets/rsa_key.pem

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write private and public key files
        run: |
          mkdir -p ${{ github.workspace }}/secrets
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}" | base64 -d > ${{ github.workspace }}/secrets/rsa_key.p8
          openssl pkey -in ${{ github.workspace }}/secrets/rsa_key.p8 -out ${{ github.workspace }}/secrets/rsa_key.pem
          openssl pkey -in ${{ github.workspace }}/secrets/rsa_key.p8 -pubout -out ${{ github.workspace }}/secrets/rsa_key.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -no-color
